### ISSUE TITLE
Cannot create Cutting station in rockhounding_rocks-1.11.2-2.01

### ISSUE THREAD

**Issue by pkazmier32** [GlobbyPotato/Rockhounding_Rocks#1]
I put the Piston and bucket in a crafting table but the Cutting Station does not appear in the output.

**Comment by GlobbyPotato** [comment]
There is also a redstone dust in the top-centre slot and the rest are iron ingots, are they visible in the recipe?

**Comment by pkazmier32** [comment]
JEI is not showing the recipe that way.  I tried this:
 Iron Ingot | Redstone Dust | Iron Ingot
 Iron Ingot | Bucket | Iron Ingot
 Iron Ingot | Piston | Iron Ingot

BTW, I love your Chemistry Mod.

**Comment by pkazmier32** [comment]
I also tried the Iron Casing IC and Basic Logic BL from your chemistry mod:

IC | BL | IC
IC | Bucket | IC
IC | Piston | IC

I tried changing around the basic logic, piston and bucket.

**Comment by GlobbyPotato** [comment]
The recipe changes depending if Chemistry is installed or not. Is any of the two recipes working? I think someone else complained in the past that the oredicted redstone was not visible in crafting.

**Comment by pkazmier32** [comment]
I have Chemistry installed.  Neither recipe seems to be working.

**Comment by GlobbyPotato** [comment]
Ok for the Chemistry compatibility I think I found the issue, being a matter of some uppercase naming persisting from 1.10. The other recipe without chemistry is working fine here, they are only vanilla items. 

Will update it soon. Sorry for the issue.

**Comment by pkazmier32** [comment]
No worries.  Thanks for your prompt attention to this.
