### ISSUE TITLE
Request - Mod support and additional pattern types

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [GlobbyPotato/Rockhounding_Rocks#10]
So as you know I love your mod but at any rate - I spent 160 hours on behalf of team chisel but they honestly treated me like shit. Your mod works. Your chisel patterns work. If I make you some rough chisel pattern ideas could you impliment them? This is what I am dealing with using the chisel mod. 
![2018-10-16 13_53_11-nvidia geforce overlay](https://user-images.githubusercontent.com/10351221/47485379-a46e6580-d803-11e8-8a42-b4c5cc3c99f2.jpg)

Your mod works and you share my passion for blocks and decoration. Please help me finish my ultimate cosmetic server.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Chisel-Team/Chisel/issues/747

https://github.com/Chisel-Team/Chisel/issues/745

https://github.com/Chisel-Team/Chisel/issues/744

https://github.com/Chisel-Team/ConnectedTexturesMod/issues/9

**Comment by GlobbyPotato** [comment]
Hi, that's really strange to hear, Chisel is the standard about decoration, I can't see the devs being harsh with players, From the image it looks like overlays are missing or they are just the palette colors not rendering the textures, or some graphical glitch, no idea from here.
Anyway, I can check what you propose and see if I can help. This mod has a specific structure though, so the patterns need to fit the various rocks to look decent at least. Of course I'd like to avoid duplications from other mods or vanilla, I'm trying to stay close to the mod's theme.

**Comment by P3rf3ctXZer0** [comment]
Oh yeah sorry they did fix it but I can still make patterns for you if you give me a template.png

**Comment by P3rf3ctXZer0** [comment]
It was fixed about 2 weeks ago.
