### ISSUE TITLE
Does the carving/sculpturebench have crafttweaker support?

### ISSUE THREAD

**Issue by Pentasis** [GlobbyPotato/Rockhounding_Rocks#11]
Just a question (title) and if not, could it be added?

**Comment by GlobbyPotato** [comment]
They are supported:
https://github.com/GlobbyPotato/Rockhounding_Rocks/blob/1.12.2/CraftTweaker_scripts.txt

**Comment by Pentasis** [comment]
Thanks, I missed that somehow.
