### ISSUE TITLE
[MC 1.12.2] Very odd crash - Sound related? 

### ISSUE THREAD

**Issue by Alaberti** [GlobbyPotato/Rockhounding_Rocks#12]
*Mod Version:*
rockhounding_core-1.12.2-3.17
rockhounding_rocks-1.12.2-3.18
DynamicSurroundings-1.12.2-3.5.4.2BETA
DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA
ImmersiveEngineering-0.12-88
SoundFilters-0.10_for_1.12

*Forge Version:*
forge-1.12.2-14.23.5.2807-universal

*Link to crash log (if applicable):*
https://paste.dimdev.org/avogadosuc.mccrash
https://paste.dimdev.org/roxivawino.mccrash

*Description:*
Game crashed with the above errors. Not sure who is ultimately responsible but RH is the prime culprit" in both crashes it seems.

**Comment by GlobbyPotato** [comment]
hi, Rocks v3.18 shouldn't match with Core v3.17
try updaing rocks to latest alpha v3.20

**Comment by Alaberti** [comment]
Yup, that was it, thanks!
