### ISSUE TITLE
Rock specific config doesnt work

### ISSUE THREAD

**Issue by Xaikii** [GlobbyPotato/Rockhounding_Rocks#13]
My plan was it to make the Stone seriously rare in my pack and therefore changed the Frequency to 1 for every stone and set the Vein Size to 1-2. And basically nothing changed. To be sure I also made multiple tries, which ended all the same. I then tried and and change the value to something high, as it is also possible to make the chance 1/x... and this basically made them overflow... I didnt even see a single stone for a few mins...

Config: https://pastebin.com/S0LUhiMA
Forge: forge-14.23.5.2825
MCVersion: 1.12.2
Rockhounding Version: rockhounding_rocks-1.12.2-3.18

**Comment by GlobbyPotato** [comment]
hi, try to set 
`B:"Clouds Enabler"=false`

and see what happens. In this way you use the specific rocks parameters (frequency and size). You should have 1 attempt to generate each rocks at Frequency=1

With Clouds Enabler = true, instead you override the specific parameters (frequency and size), setting them the same for all the rocks.
`

    # Wether to use clouds or patches generation
    B:"Clouds Enabler"=true

    # Possible clouds per chunk
    I:"Clouds Frequency"=1
 
    # Maximum cloud size
    I:"Clouds Max Size"=2
 
    # Minimum cloud size
    I:"Clouds Min Size"=1
`

check the [wiki page](https://minecraft.curseforge.com/projects/rockhounding-mod-rocks/pages/main/worldgen) for reference

**Comment by Xaikii** [comment]
hmm ok I played with it a little and it works fine now :)
but tbh the wording "cloud" is a bit confusing ^^'

anyways thanks for the help
