### ISSUE TITLE
[1.12.2] Tile error and illegal argument placing Water Wheel

### ISSUE THREAD

**Issue by alenxa** [GlobbyPotato/Rockhounding_Rocks#14]
I recently upgraded a pack including Core, Rocks, Surface, and Chemistry and the game crashed every time I would place a water wheel. Error log for the first such crash is as follows:
https://pastebin.com/LzVdf71s

So I tried going back to my previous versions of the mods, which did not cause this error in other packs, and in a different world was able to place one but got the following error when I dug out the dirt directly beneath it:
https://pastebin.com/qgbBkbd3

I'm very confused as I have multiple worlds with functional water wheels using the versions in the second report. One of them also has Dynamic Trees (which I also saw in the second log file), but an older version than in the pack that crashed. I LOVE the Rockhounding suite but I'm not a coder, so any help/guidance is appreciated. Thanks!

**Comment by GlobbyPotato** [comment]
Hi, at first look it could be a sync issue between the Core and the mods version. Try to update them all to the latest version to see if it sorts:
core v3.22
chemistry v3.38
surface v3.14
rocks v3.20
guidebook v2.9.1

**Comment by alenxa** [comment]
That seems to have been it, thanks! I wish I had waited a week to update so I would have grabbed this set right from the start. :)
