### ISSUE TITLE
[Request] Stairs and slabs

### ISSUE THREAD

**Issue by belathus** [GlobbyPotato/Rockhounding_Rocks#2]
This mod adds all kinds of neat blocks and models for each of its stone types... but no stairs or slabs.

**Comment by GlobbyPotato** [comment]
Hi, I didn't added them yet because they would require too many IDs (taling about 300+). 
I'm also figuring out how to handle the translucency issue which would make slabbing more complicated. For now I left them made with chisel&bit which is used everywhere and solves some of the issues.

**Comment by belathus** [comment]
Stairs would use a ton of IDs, so that makes a lot of sense. I'm guessing 1.13 would help with that.
