### ISSUE TITLE
[Request] [1.12.2] Support for low tech themed modpacks

### ISSUE THREAD

**Issue by NotAVerb** [GlobbyPotato/Rockhounding_Rocks#3]
The cutting station and rock vendor don't lend themselves well to any modpack lacking in industrial themed blocks.
Bibliocraft offers two functionally identical versions of an item for interacting with blocks, a screw gun and a hand drill. Maybe there could be some sort of masonry table?

Personally I find it annoying to have to install Redstone Flux when I know I'm never going to use any RF related features, especially because I'm trying to keep the number of mods I'm packing low. Which is why I was also wondering if the dependency scheme of Rockhounding could somehow be changed to be softer and only load the high tech machinery if the proper dependencies are installed.

I'd even be fine without a low tech cutting station alternative if Rockhounding Rocks could be installed standalone and would only bring new blocks and world-gen into the world. I'd just use Crafttweaker to add recipes for the blocks and pillars.

**Comment by GlobbyPotato** [comment]
The dependency system is made to keep the minimal possible the code and the maintenance time, since the core equally serves all the Rockhounding modules. The issue of having the little RF api in the pack is lower than splitting Rocks from the core. Twice the code to recreate the mod hierarchy into Rocks, twice the code in case people want to use RF instead of lava, twice maintenance to fix the same code.

Just for correct information for readers, the first period you wrote is misleading. The mod fits pack lacking industrial blocks, Aside the annoiance of having the little api installed, you only need coal/lava and water to run it. That way may sound like the mod doesn't work without RF generators.

**Comment by NotAVerb** [comment]
I'll clarify that yes my first issue is not that Rockhounding Rocks doesn't work without RF generators, but that the cutting station's design is too "high-tech" for a world lacking in the metallic and electric varieties of machinery.

**Comment by GlobbyPotato** [comment]
Ok, I think I understand now what you mean. You are basically proposing manual stonecutter tools doing the job of the Cutting Station, right? Sounds neat but I need also to preserve the identity of the mod. So I could possibly make a set of tiered no-gui tools (blocks and items) to manipulate step by step the various shapes and leave a config value if include or not the Station. You can choose if go the medieval or the hi-tech way.
The Rock vendor should not be a problem, it's just a trading block, no tech involved.

Still, your concern about adding the RF dependency remains for the reason I told you. It costs too much work doing a feature and its contrary at the same time.

**Comment by NotAVerb** [comment]
The new crafting stations are neat. I really like that I can automate the rock platform with hoppers.

Currently the Water wheels can only rotate one way. Could they be made to accept water flowing in the other direction?
Also blocks render off-center on the carving bench. Blocks on the sculpting bench are fine though.
![2018-03-06_17 29 35](https://user-images.githubusercontent.com/30223331/37062285-e3382fd0-218d-11e8-93f7-1ddf7ad36507.png)
The sculpting bench and the carving bench can both accept each others schemes.

The two Guidebook guidebooks are missing textures due to an unidentified mod conflict. The books have textures when I only install Rockhounding and Guidebook. I've confirmed that neither Foamfix nor Texfix are causing the issue.

I also see that you managed to remove the RF dependency. Thanks a lot.

**Comment by GlobbyPotato** [comment]
The animation are fixed, so the wheel can't be set in different ways. Devices must be considered on their interity.

Fixed the rendering offset, mfw a whole bunch of code in no longer there.
Fixed the scheme issue. The rack accepts them only if the right bench is correctly placed under it.

About the guidebook, I don't know, I see the textures. Does it also fail on the default book coming with the mod? Is that the latest version 2.0.1?

**Comment by NotAVerb** [comment]
The default guidebook from Guidebook breaks even if Rockhounding is absent. The issue isn't on your end.
I'll be opening an issue on the Guidebook tracker if I figure out which mod is breaking the texture.

edit: Turns out it wasn't even a mod conflict. The problem lay with Guidebook itself. The Twitch launcher downloaded an outdated release, the latest beta fixed the issue.
