### ISSUE TITLE
[1.12.2] Missing recipes

### ISSUE THREAD

**Issue by NotAVerb** [GlobbyPotato/Rockhounding_Rocks#5]
Version 3.06

The polished blocks are missing recipes for these following blocks. All of them are from vanilla minecraft.
The sixteen colors of hardened clay,
Stone,
Both varieties of nether bricks,
Sandstone,
Red Sandstone,
Bone,
End Stone,
Prismarine,
Nether Quartz,
Nether Wart,
and Snow.

Granite, diorite, and andestite are also missing recipes for polished blocks. However, vanilla polished blocks for these stones already exist.

**Comment by GlobbyPotato** [comment]
Added them, those recipe were not active yet even in the cutting station.
Made a big recipe refactoring. Patiently tested all, hopefully nothing broke.
