### ISSUE TITLE
Majority of blocks are not graphicaly compatible with chisel and bits

### ISSUE THREAD

**Issue by NotAVerb** [GlobbyPotato/Rockhounding_Rocks#8]
I installed chisel and bits upon your recommendation to acquire stairs and slabs only to find that chiseling any of the blocks carved from plain blocks breaks their texture. Making it impossible to create slabs and stairs for these blocks.
![2018-03-14_20 06 19](https://user-images.githubusercontent.com/30223331/37437787-f95e4196-27e6-11e8-850a-34a899d86bf8.png)

**Comment by GlobbyPotato** [comment]
Now this is a terrible news. I remember C&B used to save the patterns back when I tested it. That helped a lot by delegating all these block making. I don't know when this part changed or if it needs a kind of integration.
Oh well, will probably need to retexture all the old way so C&B will recognize them, This should also solve the translucency issue with shaders at once.
Adding stairs and slabs on their own will cause a huge increase of id so it's not even considerable. You'll have to wait a little for the slab fix.
