### ISSUE TITLE
Server crash on startup with Guidebook

### ISSUE THREAD

**Issue by AdaraChristine** [GlobbyPotato/Rockhounding_Rocks#9]
Gigaherz  said i should let you know about this. Thanks

"Hello, so far these crashes have been fixable by the mods using Guidebook adding "after:gbook" as a dependency sorting rule. " gigaherz 

https://github.com/gigaherz/Guidebook/issues/56

**Comment by GlobbyPotato** [comment]
woooops, I always thought I declared it on the Rocks module too, being guidebook a required dependency.
Fix is under review on the site. should pop out soon.

**Comment by AdaraChristine** [comment]
Thanks for all your hard work!
